#pragma once

namespace Anemone
{
    enum class BlockCipherPaddingMode
    {
        // Fills padding area appending single '1' bit and many '0'.
        Bits,

        /// Fills padding area using zeroed bytes.
        ///
        /// @verbatim
        /// xx xx xx 00 00 00 00 00
        /// @endverbatim
        Zero,

        /// Fills padding area using zeroed bytes, except last byte which contains number of filled
        /// bytes
        ///
        /// @verbatim
        /// xx xx xx 00 00 00 00 05
        /// @endverbatim
        ANSIX923,

        /// Fills padding area using random generated bytes, except last byte which contains number
        /// of filled bytes.
        ///
        /// @verbatim
        /// xx xx xx 38 F2 CD 9F 05
        /// @endverbatim
        ISO10126,

        /// Fills padding area using value which is number of filled bytes.
        ///
        /// @verbatim
        /// xx xx xx 05 05 05 05 05
        /// @endverbatim
        PKCS7,

        /// Fills padding area using 80 (00) byte pattern.
        ///
        /// @verbatim
        /// xx xx xx 80 00 00 00 00
        /// @endverbatim
        ISOIEC78164,
    };
}
