#include "AnemoneRuntime/ErrorCode.hxx"

#include "AnemoneRuntime/Platform/Windows/WindowsInterop.hxx"

namespace Anemone::System::Private
{
    ErrorCode ErrorCodeFromWin32Error(uint32_t error)
    {
        switch (error)
        {
        case ERROR_INVALID_FUNCTION:
            return ErrorCode::FunctionNotSupported;
        case ERROR_FILE_NOT_FOUND:
            return ErrorCode::NoSuchFileOrDirectory;
        case ERROR_PATH_NOT_FOUND:
            return ErrorCode::NoSuchFileOrDirectory;
        case ERROR_MOD_NOT_FOUND:
            return ErrorCode::NoSuchFileOrDirectory;
        case ERROR_TOO_MANY_OPEN_FILES:
            return ErrorCode::TooManyFilesOpen;
        case ERROR_ACCESS_DENIED:
            return ErrorCode::PermissionDenied;
        case ERROR_INVALID_HANDLE:
            return ErrorCode::InvalidArgument;
        case ERROR_NOT_ENOUGH_MEMORY:
            return ErrorCode::NotEnoughMemory;
        case ERROR_INVALID_ACCESS:
            return ErrorCode::PermissionDenied;
        case ERROR_OUTOFMEMORY:
            return ErrorCode::NotEnoughMemory;
        case ERROR_INVALID_DRIVE:
            return ErrorCode::NoSuchDevice;
        case ERROR_CURRENT_DIRECTORY:
            return ErrorCode::PermissionDenied;
        case ERROR_NOT_SAME_DEVICE:
            return ErrorCode::CrossDeviceLink;
        case ERROR_WRITE_PROTECT:
            return ErrorCode::PermissionDenied;
        case ERROR_BAD_UNIT:
            return ErrorCode::NoSuchDevice;
        case ERROR_NOT_READY:
            return ErrorCode::ResourceUnavailableTryAgain;
        case ERROR_SEEK:
            return ErrorCode::IoError;
        case ERROR_WRITE_FAULT:
            return ErrorCode::IoError;
        case ERROR_READ_FAULT:
            return ErrorCode::IoError;
        case ERROR_SHARING_VIOLATION:
            return ErrorCode::PermissionDenied;
        case ERROR_LOCK_VIOLATION:
            return ErrorCode::NoLockAvailable;
        case ERROR_HANDLE_DISK_FULL:
            return ErrorCode::NoSpaceOnDevice;
        case ERROR_NOT_SUPPORTED:
            return ErrorCode::NotSupported;
        case ERROR_BAD_NETPATH:
            return ErrorCode::NoSuchFileOrDirectory;
        case ERROR_DEV_NOT_EXIST:
            return ErrorCode::NoSuchDevice;
        case ERROR_BAD_NET_NAME:
            return ErrorCode::NoSuchFileOrDirectory;
        case ERROR_FILE_EXISTS:
            return ErrorCode::FileExists;
        case ERROR_CANNOT_MAKE:
            return ErrorCode::PermissionDenied;
        case ERROR_INVALID_PARAMETER:
            return ErrorCode::InvalidArgument;
        case ERROR_BROKEN_PIPE:
            return ErrorCode::BrokenPipe;
        case ERROR_OPEN_FAILED:
            return ErrorCode::IoError;
        case ERROR_BUFFER_OVERFLOW:
            return ErrorCode::FileNameTooLong;
        case ERROR_DISK_FULL:
            return ErrorCode::NoSpaceOnDevice;
        case ERROR_SEM_TIMEOUT:
            return ErrorCode::TimedOut;
        case ERROR_INVALID_NAME:
            return ErrorCode::NoSuchFileOrDirectory;
        case ERROR_NEGATIVE_SEEK:
            return ErrorCode::InvalidArgument;
        case ERROR_BUSY_DRIVE:
            return ErrorCode::DeviceOrResourceBusy;
        case ERROR_DIR_NOT_EMPTY:
            return ErrorCode::DirectoryNotEmpty;
        case ERROR_BUSY:
            return ErrorCode::DeviceOrResourceBusy;
        case ERROR_ALREADY_EXISTS:
            return ErrorCode::FileExists;
        case ERROR_FILENAME_EXCED_RANGE:
            return ErrorCode::FileNameTooLong;
        case ERROR_LOCKED:
            return ErrorCode::NoLockAvailable;
        case WAIT_TIMEOUT:
            return ErrorCode::TimedOut;
        case ERROR_DIRECTORY:
            return ErrorCode::InvalidArgument;
        case ERROR_OPERATION_ABORTED:
            return ErrorCode::OperationCanceled;
        case ERROR_NOACCESS:
            return ErrorCode::PermissionDenied;
        case ERROR_CANTOPEN:
            return ErrorCode::IoError;
        case ERROR_CANTREAD:
            return ErrorCode::IoError;
        case ERROR_CANTWRITE:
            return ErrorCode::IoError;
        case ERROR_RETRY:
            return ErrorCode::ResourceUnavailableTryAgain;
        case ERROR_TIMEOUT:
            return ErrorCode::TimedOut;
        case ERROR_OPEN_FILES:
            return ErrorCode::DeviceOrResourceBusy;
        case ERROR_DEVICE_IN_USE:
            return ErrorCode::DeviceOrResourceBusy;
        case ERROR_REPARSE_TAG_INVALID:
            return ErrorCode::InvalidArgument;
        case WSAEINTR:
            return ErrorCode::Interrupted;
        case WSAEBADF:
            return ErrorCode::BadFileDescriptor;
        case WSAEACCES:
            return ErrorCode::PermissionDenied;
        case WSAEFAULT:
            return ErrorCode::BadAddress;
        case WSAEINVAL:
            return ErrorCode::InvalidArgument;
        case WSAEMFILE:
            return ErrorCode::TooManyFilesOpen;
        case WSAEWOULDBLOCK:
            return ErrorCode::OperationWouldBlock;
        case WSAEINPROGRESS:
            return ErrorCode::OperationInProgress;
        case WSAEALREADY:
            return ErrorCode::ConnectionAlreadyInProgress;
        case WSAENOTSOCK:
            return ErrorCode::NotASocket;
        case WSAEDESTADDRREQ:
            return ErrorCode::DestinationAddressRequired;
        case WSAEMSGSIZE:
            return ErrorCode::MessageSize;
        case WSAEPROTOTYPE:
            return ErrorCode::WrongProtocolType;
        case WSAENOPROTOOPT:
            return ErrorCode::NoProtocolOption;
        case WSAEPROTONOSUPPORT:
            return ErrorCode::ProtocolNotSupported;
        case WSAEOPNOTSUPP:
            return ErrorCode::OperationNotSupported;
        case WSAEAFNOSUPPORT:
            return ErrorCode::AddressFamilyNotSupported;
        case WSAEADDRINUSE:
            return ErrorCode::AddressInUse;
        case WSAEADDRNOTAVAIL:
            return ErrorCode::AddressNotAvailable;
        case WSAENETDOWN:
            return ErrorCode::NetworkDown;
        case WSAENETUNREACH:
            return ErrorCode::NetworkUnreachable;
        case WSAENETRESET:
            return ErrorCode::NetworkReset;
        case WSAECONNABORTED:
            return ErrorCode::ConnectionAborted;
        case WSAECONNRESET:
            return ErrorCode::ConnectionReset;
        case WSAENOBUFS:
            return ErrorCode::NoBufferSpace;
        case WSAEISCONN:
            return ErrorCode::AlreadyConnected;
        case WSAENOTCONN:
            return ErrorCode::NotConnected;
        case WSAETIMEDOUT:
            return ErrorCode::TimedOut;
        case WSAECONNREFUSED:
            return ErrorCode::ConnectionRefused;
        case WSAENAMETOOLONG:
            return ErrorCode::FileNameTooLong;
        case WSAEHOSTUNREACH:
            return ErrorCode::HostUnreachable;

        default:
            break;
        }

        return ErrorCode::Unknown;
    }
}
