include_guard()

#set(CMAKE_CXX_COMPILER_ARCHITECTURE_ID "arm64")

set(LLVM_PATH "C:/Program Files/LLVM/bin")

set(CMAKE_C_COMPILER    "${LLVM_PATH}/clang.exe")
set(CMAKE_CXX_COMPILER  "${LLVM_PATH}/clang++.exe")
set(CMAKE_LINKER        "${LLVM_PATH}/lld.exe")
set(CMAKE_AR            "${LLVM_PATH}/llvm-ar.exe")

set(TOOLCHAIN_COMMON_COMPILER_FLAGS
    "-DUNICODE -D_UNICODE"
)

set(TOOLCHAIN_COMMON_CXX_FLAGS
    ""
)

set(TOOLCHAIN_COMMON_C_FLAGS
    ""
)

set(TOOLCHAIN_COMMON_COMPILER_FLAGS "${TOOLCHAIN_COMMON_COMPILER_FLAGS} -march=armv8-a -mtune=generic")

set(CMAKE_CXX_FLAGS_INIT "${TOOLCHAIN_COMMON_COMPILER_FLAGS} ${TOOLCHAIN_COMMON_CXX_FLAGS}")
set(CMAKE_C_FLAGS_INIT   "${TOOLCHAIN_COMMON_COMPILER_FLAGS} ${TOOLCHAIN_COMMON_C_FLAGS}")

set(TOOLCHAIN_COMPILER_DEBUG_FLAGS      "-O0")
set(TOOLCHAIN_COMPILER_DEVELOPER_FLAGS  "-O1")
set(TOOLCHAIN_COMPILER_PROFILING_FLAGS  "-O3 -g -DNDEBUG -flto")
set(TOOLCHAIN_COMPILER_SHIPPING_FLAGS   "-O3 -g -DNDEBUG -flto")

set(TOOLCHAIN_LINK_FLAGS)

set(TOOLCHAIN_LINK_DEBUG_FLAGS          "${TOOLCHAIN_LINK_FLAGS}")
set(TOOLCHAIN_LINK_DEVELOPER_FLAGS      "${TOOLCHAIN_LINK_FLAGS}")
set(TOOLCHAIN_LINK_PROFILING_FLAGS      "${TOOLCHAIN_LINK_FLAGS}")
set(TOOLCHAIN_LINK_SHIPPING_FLAGS       "${TOOLCHAIN_LINK_FLAGS}")

set(CMAKE_C_FLAGS_DEBUG                 "${TOOLCHAIN_COMPILER_DEBUG_FLAGS}")
set(CMAKE_C_FLAGS_DEVELOPER             "${TOOLCHAIN_COMPILER_DEVELOPER_FLAGS}")
set(CMAKE_C_FLAGS_PROFILING             "${TOOLCHAIN_COMPILER_PROFILING_FLAGS}")
set(CMAKE_C_FLAGS_SHIPPING              "${TOOLCHAIN_COMPILER_SHIPPING_FLAGS}")

set(CMAKE_CXX_FLAGS_DEBUG               "${TOOLCHAIN_COMPILER_DEBUG_FLAGS}")
set(CMAKE_CXX_FLAGS_DEVELOPER           "${TOOLCHAIN_COMPILER_DEVELOPER_FLAGS}")
set(CMAKE_CXX_FLAGS_PROFILING           "${TOOLCHAIN_COMPILER_PROFILING_FLAGS}")
set(CMAKE_CXX_FLAGS_SHIPPING            "${TOOLCHAIN_COMPILER_SHIPPING_FLAGS}")

set(CMAKE_EXE_LINKER_FLAGS_DEBUG        "${TOOLCHAIN_LINK_DEBUG_FLAGS} -fPIE")
set(CMAKE_EXE_LINKER_FLAGS_DEVELOPER    "${TOOLCHAIN_LINK_DEVELOPER_FLAGS} -fPIE")
set(CMAKE_EXE_LINKER_FLAGS_PROFILING    "${TOOLCHAIN_LINK_PROFILING_FLAGS} -fPIE")
set(CMAKE_EXE_LINKER_FLAGS_SHIPPING     "${TOOLCHAIN_LINK_SHIPPING_FLAGS} -fPIE")

set(CMAKE_STATIC_LINKER_FLAGS_DEBUG     "${TOOLCHAIN_LINK_DEBUG_FLAGS}")
set(CMAKE_STATIC_LINKER_FLAGS_DEVELOPER "${TOOLCHAIN_LINK_DEVELOPER_FLAGS}")
set(CMAKE_STATIC_LINKER_FLAGS_PROFILING "${TOOLCHAIN_LINK_PROFILING_FLAGS}")
set(CMAKE_STATIC_LINKER_FLAGS_SHIPPING  "${TOOLCHAIN_LINK_SHIPPING_FLAGS}")

set(CMAKE_SHARED_LINKER_FLAGS_DEBUG     "${TOOLCHAIN_LINK_DEBUG_FLAGS} -fPIE -dynamic")
set(CMAKE_SHARED_LINKER_FLAGS_DEVELOPER "${TOOLCHAIN_LINK_DEVELOPER_FLAGS} -fPIE -dynamic")
set(CMAKE_SHARED_LINKER_FLAGS_PROFILING "${TOOLCHAIN_LINK_PROFILING_FLAGS} -fPIE -dynamic")
set(CMAKE_SHARED_LINKER_FLAGS_SHIPPING  "${TOOLCHAIN_LINK_SHIPPING_FLAGS} -fPIE -dynamic")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
