# Validate 64-bit target platform

message(STATUS "CMAKE_CXX_COMPILER_ID:              '${CMAKE_CXX_COMPILER_ID}'")
message(STATUS "CMAKE_SYSTEM_PROCESSOR:             '${CMAKE_SYSTEM_PROCESSOR}'")
message(STATUS "CMAKE_CXX_COMPILER_ARCHITECTURE_ID: '${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}'")

if (MSVC)
    if (CMAKE_CXX_COMPILER_ARCHITECTURE_ID STREQUAL "ARM64")
        set(ANEMONE_ARCHITECTURE_ARM64 ON)
    elseif (CMAKE_CXX_COMPILER_ARCHITECTURE_ID STREQUAL "x64")
        set(ANEMONE_ARCHITECTURE_X64 ON)
        set(ANEMONE_FEATURE_SVML ON)
    endif()
endif()

if (CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    if (CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
        set(ANEMONE_ARCHITECTURE_ARM64 ON)
    endif()

    if (CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|x64|amd64")
        set(ANEMONE_ARCHITECTURE_X64 ON)
    endif()

    if (CMAKE_CXX_COMPILER_ARCHITECTURE_ID STREQUAL "aarch64")
        set(ANEMONE_ARCHITECTURE_ARM64 ON)
    elseif (CMAKE_CXX_COMPILER_ARCHITECTURE_ID STREQUAL "x86_64")
        set(ANEMONE_ARCHITECTURE_X64 ON)
        set(ANEMONE_FEATURE_SVML ON)
    endif()
endif()
